services:
  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: inventory-management:latest
    container_name: inventory_app
    restart: unless-stopped

    ports:
      - "1236:4002"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    env_file:
      - .env

    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 1234

      REDIS_HOST: host.docker.internal
      REDIS_PORT: 1235

    volumes:
      - ../../storage:/var/www/html/storage
      - ../../bootstrap/cache:/var/www/html/bootstrap/cache

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:4002 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
