services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_IMAGE:-inventory-service:latest}
    container_name: inventory_app
    restart: unless-stopped
    ports:
      - "1236:4002"
    env_file: [.env]
    depends_on:
      - mysql
      - redis
    networks: [app-network]
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    command: >
      sh -c "
      php artisan serve --host=0.0.0.0 --port=4002
      "

  mysql:
    image: mysql:8.0
    container_name: inventory_mysql
    restart: unless-stopped
    ports:
      - "1234:3306"
    env_file: [.env]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks: [app-network]

  redis:
    image: redis/redis-stack:latest
    container_name: inventory_redis
    restart: unless-stopped
    ports:
      - "1235:8001"
    env_file: [.env]
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    networks: [app-network]
    volumes:
      - redis_data:/data
      - redisinsight_data:/redisinsight

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  redisinsight_data:
