ervices:
  mysql:
    image: mysql:8.0
    container_name: inventory_mysql
    restart: unless-stopped
    ports:
      - "1234:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  mysql_init_extra_user:
    image: mysql:8.0
    container_name: inventory_mysql_init_user
    depends_on:
      mysql:
        condition: service_healthy
    restart: "no"
    command: >
      bash -lc "
        mysql -hmysql -uroot -p'' -e \"
          CREATE USER IF NOT EXISTS 'exp_user'@'%' IDENTIFIED BY '';
          GRANT ALL PRIVILEGES ON .* TO 'exp_user'@'%';
          FLUSH PRIVILEGES;
        \"
      "

volumes:
  mysql_data:
