services:
  mysql:
    image: mysql:8.0
    container_name: inventory_mysql
    restart: unless-stopped
    ports:
      - "${DOCKER_MYSQL_PORT_EXTERNAL:-1234}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [ app-network ]

  redis:
    image: redis/redis-stack:latest
    container_name: inventory_redis
    restart: unless-stopped
    ports:
      - "${DOCKER_REDIS_PORT_EXTERNAL:-1235}:8001"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [ app-network ]
    volumes:
      - redis_data:/data
      - redisinsight_data:/redisinsight

  app:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ${APP_IMAGE:-inventory-management}
    container_name: inventory_app
    restart: unless-stopped
    ports:
      - "${DOCKER_APP_PORT_EXTERNAL:-1236}:${DOCKER_APP_PORT_INTERNAL:-4002}"

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks: [ app-network ]
    volumes:
      - ../../storage:/var/www/html/storage
      - ../../bootstrap/cache:/var/www/html/bootstrap/cache
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:${DOCKER_APP_PORT_INTERNAL:-4002} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  redisinsight_data:
